print('Dissecando uma Variável')
vr1 = input('Digite algo: ')
#vr2 = type(vr1)
#vr3 = (vr1.isspace())
#vr4 = (vr1.isnumeric())
#vr5 = (vr1.isalpha())
#vr6 = (vr1.isalnum())
#vr7 = (vr1.isupper())
#vr8 = (vr1.islower())
#vr9 = (vr1.capitalize())
#print('O tipo primitivo do valor digitado é {}'.format(vr2))
#print('Só tem espaços? {}'.format(vr3))
#print('É um número? {}'.format(vr4))
#print('É alfabético? {}'.format(vr5))
#print('É alfanumérico? {}'.format(vr6))
#print('Está em maiúscula? {}'.format(vr7))
#print('Está em minúscula? {}'.format(vr8))
#print('Está capitalizada? {}'.format(vr9))
print('O tipo primitivo do valor digitado é ',type(vr1))
print('Só tem espaços? ',vr1.isspace())
print('É um número? ',vr1.isnumeric())
print('É alfabético? ',vr1.isalpha())
print('É alfanumérico? ',vr1.isalnum())
print('Está em maiúscula? ',vr1.isupper())
print('Está em minúscula? ',vr1.islower())
print('Está capitalizada? ',vr1.istitle())


